BEGIN;

ALTER TABLE portfolios
  ALTER COLUMN user_id SET NOT NULL,
  ALTER COLUMN coin_id SET NOT NULL,
  ALTER COLUMN amount SET NOT NULL;

ALTER TABLE transactions
  ALTER COLUMN user_id SET NOT NULL,
  ALTER COLUMN coin_id SET NOT NULL;

ALTER TABLE bets
  ALTER COLUMN user_id SET NOT NULL;

COMMIT;
